# 1. 狐耳舰娘（v2 定稿版，近景）                                                                                                                                                                                                                                                  
./txt2img.sh -s 207 -o fox_staff -p "masterpiece, best quality, very aesthetic, 1girl, fox ears, fox tail, azur lane, shipgirl, huge breasts, deep cleavage, black slingshot swimsuit, open jacket draped off shoulders, thin clothes, taut clothes, bare shoulders, navel, holding staff, seductive smirk, wink, looking at viewer, detailed beautiful face, cel shading, space background, huge planet, starry sky, small spaceships, glowing blue thrusters, wide shot, spread legs, creampied, climax, full body"                                                                                                        
                                                                                                                                                                                                                                                                                 
# 2. 兔耳步枪娘                                                                                                                                                                                                                                                                   
./txt2img.sh -s 202 -o bunny_rifle -p "masterpiece, best quality, very aesthetic, 1girl, bunny ears, azur lane, shipgirl, long silver hair, huge breasts, deep cleavage, white slingshot swimsuit, open military jacket draped off shoulders, thin clothes, taut clothes, bare shoulders, navel, holding rifle,    
flirtatious smile, looking at viewer, detailed beautiful face, cel shading, space background, huge planet, starry sky, small spaceships, glowing blue thrusters, wide shot"                                                                                                         
                                                                                                                                                                                                                                                                                 
# 3. 黑长直刀娘                                                                                                                                                                                                                                                                   
./txt2img.sh -s 203 -o katana -p "masterpiece, best quality, very aesthetic, 1girl, long black hair, hime cut, azur lane, shipgirl, huge breasts, deep cleavage, red and black slingshot swimsuit, thin clothes, taut clothes, bare shoulders, navel, katana, rare seductive smile, looking at viewer,        
detailed beautiful face, cel shading, space background, full moon, starry sky, wide shot"                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                 
# 4. 双马尾无人机娘                                                                                                                                                                                                                                                               
./txt2img.sh -s 204 -o twintail_drone -p "masterpiece, best quality, very
  aesthetic, 1girl, twintails, blonde hair, azur lane, shipgirl, huge
  breasts, deep cleavage, white and blue slingshot swimsuit, thin clothes,
  taut clothes, bare shoulders, navel, floating drones, playful seductive
  smile, looking at      viewer, detailed beautiful face, cel shading, space
  background, huge planet, starry sky, wide shot"  
                                                                                                                                                                                                                                                                                 
# 5. 紫发魔女（v2 定稿版，近景）                                                                                                                                                                                                                                                  
./txt2img.sh -s 208 -o witch -p "masterpiece, best quality, very aesthetic, 1girl, purple hair, witch hat, azur lane, shipgirl, huge breasts, deep cleavage, dark purple slingshot swimsuit, open robe draped off shoulders, thin clothes, taut clothes, bare shoulders, navel, magic staff, mysterious      
seductive smile, looking at viewer, detailed beautiful face, cel shading, space background, glowing nebula, starry sky, wide shot"                                                                                                                              
                                                                                                                                                                                                                                                                                 
# 6. 红发恶魔娘                                                                                                                                                                                                                                                                   
./txt2img.sh -s 206 -o demon -p "masterpiece, best quality, very aesthetic, 1girl, demon horns, red hair, azur lane, shipgirl, huge breasts, deep cleavage, black and gold slingshot swimsuit, thin clothes, taut clothes, bare shoulders, navel, bat wings, teasing seductive grin, looking at viewer,      
detailed beautiful face, cel shading, space background, huge planet, starry sky, small spaceships, glowing blue thrusters, wide shot"  